services:
  # ----------------------
  # Databases
  # ----------------------
  valkey:
    image: valkey/valkey:latest
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - valkey_data:/data
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ${POSTGRES_VOLUME}:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    depends_on:
      - postgres
      - valkey
    restart: unless-stopped

volumes:
  valkey_data:
  pgdata:
