name: 🐛 Bug Report
description: Report a bug
title: '[Bug]: '
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug. Please complete all fields.

  - type: input
    id: env
    attributes:
      label: Environment
      description: Browser, OS, DB, etc.
      placeholder: "e.g., Chrome 125, macOS, PostgreSQL 15"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: "1. Go to...\n2. Click on...\n3. See error"
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
    validations:
      required: true
