name: ✨ Feature Request
description: Suggest a new feature
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your suggestion!

  - type: textarea
    id: description
    attributes:
      label: Feature Description
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Why Is This Feature Needed?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
    validations:
      required: false
