name: Go Backend

on:
  push:
    branches:
      - main
      - dev
      - feature/**
      - fix/**
      - docs/**
      - ci/**
  pull_request:
    branches:
      - main
      - dev

env:
  GO_VERSION: "1.25"

jobs:
  build-and-test:
    name: Build, Test, and Lint
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Download Dependencies
        run: go mod download

      - name: Build Binary
        run: go build -v ./cmd/api

      - name: Run Unit Tests
        run: go test ./... -v -cover

      # - name: 🧹 (Optional) Lint with golangci-lint
      #   if: always()
      #   uses: golangci/golangci-lint-action@v6
      #   with:
      #     version: latest
      #     working-directory: backend
      #     args: --timeout 3m
