name: Go Backend

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  GO_VERSION: '1.24'

jobs:
  build-and-test:
    name: Build, Test, and Lint
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Install dependencies
        run: go mod download

      - name: Build binary
        run: go build -v ./cmd/api

      - name: Run tests
        run: go test ./... -v -cover

      # - name: Lint with golangci-lint
      #   uses: golangci/golangci-lint-action@v6
      #   with:
      #     version: latest
      #     working-directory: backend
      #     args: --timeout 3m

