name: License Header Check

on:
  pull_request:
  push:

jobs:
  license:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check for license headers
        run: ./scripts/check_license.sh
